ntrain: 1000  # default 10000 how many images per epoch
nvalid: 100  # default 1000
batch_size_gen: 4  # default 2
# Number of emitters per image
num_particles_range: [800, 801]  # with a strong gpu [450, 550]
image_volume: [200, 200, 30]  # the volume of imaging each dimension in um (i think these are in camera coordinates)
particle_spatial_range_xy: [15, 185]  # dependence on the volume size default 200 um
# um, to avoid edges of the image so 15 um away
particle_spatial_range_z: [-10, 11, 1]  # um default range(-10,11,1)
# Define the parameters
N: 500  # grid size
px: 1.0e-6  # pixel size [m]
focal_length: 2.0e-3  # [m] equivalent to 2 mm away from the lens
wavelength: 0.561e-6  # [m]
refractive_index: 1.0  # We assume propagation is in air
psf_width_pixels: 101  # How big will be the psf image
psf_edge_remove: 15
psf_keep_radius: 15
numerical_aperture: 0.6  # Relates to the resolution of the detection objective
bead_radius: 1.0  # pixels 1.0 default, can change to make larger beads
random_seed: 12345
initial_learning_rate: 0.01
batch_size: 1
max_epochs: 21
mask_phase_pixels: 500
data_path: "beads_img_defocus"
path_save: "data_mask_learning"
path_train: "traininglocations"
ori_intensity: 20000  # arbitrary units
laser_beam_FWHC: 0.0001  # in um, the size of the FWHM of the Gaussian beam
max_defocus: 41  # um for generating the PSFs
learning_rate_scheduler_factor: 0.1
learning_rate_scheduler_patience: 5
learning_rate_scheduler_patience_min_lr: 1.0e-6
max_intensity: 5.0e+4
# In case that the network needs to downsample the image, GPU memory issues
ratio_input_output_image_size: 1  # default with Unet 1, with ResNet 4
# How many planes to consider as right classification, besides the plane
# in focus, if 1 the -1, in focus, and +1 plane will be considered correct
# if 0, only the infocus plane is considered, default value 1
z_range_cost_function: 0 # default 1
use_unet: true
num_classes: 1
lens_approach: "fresnel" # "fourier" or "fresnel"
power_2: 1000 # pad to this power for fourier transform
bfp_dir: "back_focal_plane"
dropout: 0.5